name: Build and deploy Angular app to Azure Web App - product-import-ui

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Install dependencies
        run: npm install

      - name: Build Angular app
        run: npm run build --if-present

      # 👉 chỉ upload thư mục dist/import_product_fe/browser
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: angular-dist
          path: dist/import_product_fe/browser/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: angular-dist

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_DC0781FB898B43EA880F79C87A73033A }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_612240515E6C41F1BE4F09AC5C378149 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_A6ACF2504D9C47ABB2AAD6C9AA0F621E }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'product-import-ui'
          slot-name: 'Production'
          package: .
